#!/usr/bin/env bash
# Run this ON the baremetal core/IMS host, ideally right after reproducing a
# failed REGISTER with sip/register_test.py, to gather the evidence needed to
# tell WHERE in the chain a rejection like:
#   403 Forbidden - Private identity not found (Authorization: username)
# is actually coming from. That message is generated by Kamailio's IMS
# registrar logic once it has a username to look up -- so seeing it (rather
# than a routing failure/timeout) means a node DID engage with the identity
# and could not resolve it. The three live possibilities, in likely order:
#   1. The subscriber doesn't exist in the HSS/subscriber DB at all yet.
#   2. It exists for 5G (AMF/SMF slice+DNN) but has no IMS/Cx profile, so the
#      HSS's Cx lookup (User-Authorization or Multimedia-Auth) comes back
#      "unknown user" even though the IMSI is real.
#   3. The S-CSCF/I-CSCF <-> HSS Cx Diameter peer connection itself never
#      came up (FQDN/realm mismatch), so no Cx request could even be sent.
# This script can only check #1 mechanically and surface the HSS log (which
# is the only log path we know for certain from your config); it prints
# guidance for #2/#3 rather than guessing, since Kamailio's own log
# destination depends on your install.
set -uo pipefail

IMSI="${1:-001010000000001}"
IMS_DOMAIN="${IMS_DOMAIN:-ims.mnc001.mcc001.3gppnetwork.org}"
MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-}"
HSS_DB="${HSS_DB:-hss_db}"
IDENTITY_IMPI="${IMSI}@${IMS_DOMAIN}"

mysqlx() {
    if [ -n "$MYSQL_ROOT_PASSWORD" ]; then
        mysql -N -u root -p"${MYSQL_ROOT_PASSWORD}" "$HSS_DB" -e "$1" 2>/dev/null
    else
        sudo mysql -N "$HSS_DB" -e "$1" 2>/dev/null
    fi
}

echo "== 0. Is anything actually listening on the Cx Diameter port (3868)? =="
if command -v ss >/dev/null 2>&1; then
    hit=$(sudo ss -ltnp 2>/dev/null | grep ':3868 ' || true)
    if [ -n "$hit" ]; then
        echo "  Something is listening on :3868 -- good, at least a Cx server process exists:"
        echo "$hit" | sed 's/^/  /'
    else
        echo "  NOTHING is listening on :3868 anywhere on this host."
        echo "  That alone fully explains a 403 'Private identity not found': I-CSCF/S-CSCF"
        echo "  have a Diameter peer configured for hss.ims.mnc001.mcc001.3gppnetwork.org:3868"
        echo "  (see icscf.xml / scscf.xml), but there is no HSS process actually serving Cx"
        echo "  for them to talk to. open5gs's own hssd is Mongo-backed and, per your"
        echo "  systemctl status, isn't even running -- so if you intended a separate"
        echo "  MySQL-backed Cx HSS (e.g. the Open IMS Core 'FHoSS'), check whether that"
        echo "  service is installed and running at all."
    fi
else
    echo "  'ss' not available -- try: sudo lsof -i :3868   or   sudo netstat -ltnp | grep 3868"
fi

echo
echo "== 1. Direct check against FHoSS's '${HSS_DB}' MySQL DB for ${IDENTITY_IMPI} =="
echo "  (override DB name with HSS_DB=..., password with MYSQL_ROOT_PASSWORD=... if needed)"
if command -v mysql >/dev/null 2>&1; then
    if ! mysqlx "SELECT 1;" | grep -q 1; then
        echo "  Could not connect to '${HSS_DB}'. Either it's named differently on this host"
        echo "  (pass HSS_DB=<name>) or needs credentials (MYSQL_ROOT_PASSWORD=...)."
        echo "  Databases actually present:"
        (sudo mysql -N -e "SHOW DATABASES;" 2>/dev/null || mysql -N -u root -p -e "SHOW DATABASES;" 2>/dev/null) | sed 's/^/    /'
    else
        impi_row=$(mysqlx "SELECT id, identity, auth_scheme FROM impi WHERE identity='${IDENTITY_IMPI}';")
        if [ -z "$impi_row" ]; then
            echo "  NOT FOUND: no row in impi for identity='${IDENTITY_IMPI}'."
            echo "  This alone fully explains the 403 -- add it (edit SUBSCRIBERS in your"
            echo "  add_subscriber.sh and re-run it), or test against an IMSI that's already"
            echo "  provisioned. Currently provisioned IMPIs:"
            mysqlx "SELECT identity FROM impi;" | sed 's/^/    /'
        else
            echo "  FOUND: impi row = $impi_row"
            echo "  Linked impu(s):"
            impi_id=$(echo "$impi_row" | awk '{print $1}')
            mysqlx "SELECT impu.identity, impu.can_register FROM impi_impu
                    JOIN impu ON impu.id = impi_impu.id_impu
                    WHERE impi_impu.id_impi = ${impi_id};" | sed 's/^/    /'
            echo "  If this all looks right and you STILL get 403, the identity is provisioned"
            echo "  correctly and the problem is upstream -- go straight to section 0 (is FHoSS"
            echo "  actually listening on 3868?) and section 3 (Kamailio/FHoSS logs) below."
        fi
    fi
else
    echo "  mysql client not on PATH."
fi

echo
echo "== 1b. (secondary) 5G/Mongo subscriber DB -- NOT what Cx uses, just for completeness =="
if command -v open5gs-dbctl >/dev/null 2>&1; then
    open5gs-dbctl showall 2>/dev/null | grep -q "\"imsi\" : \"${IMSI}\"" \
        && echo "  imsi-${IMSI} exists on the 5G/Mongo side too." \
        || echo "  imsi-${IMSI} not found on the 5G/Mongo side either (irrelevant to Cx, but"
    echo "  worth knowing if you also want this subscriber to attach over 5G)."
else
    echo "  open5gs-dbctl not on PATH -- skip; irrelevant to the Cx/403 issue anyway."
fi

echo
echo "== 2. Locate the actual Cx-serving HSS process (it's FHoSS, not open5gs's hssd) =="
echo "  Your subscriber data lives in MySQL '${HSS_DB}' (FHoSS schema), and open5gs's own"
echo "  hssd isn't running per your systemctl status -- so whatever answers Cx is a"
echo "  separate process (FHoSS's Java server). Find it:"
echo "    ps aux | grep -i -E 'hss|fhoss|java' | grep -v grep"
echo "    systemctl list-units --type=service --all | grep -i hss"
echo "  If nothing turns up, combined with section 0 finding nothing on :3868, that IS"
echo "  the root cause: the HSS side of Cx was never started, independent of whether"
echo "  ${IDENTITY_IMPI} is correctly provisioned in ${HSS_DB}."
echo
echo "  (open5gs's own /var/log/open5gs/hss.log, if present, belongs to hssd -- which per"
echo "  your systemctl status isn't running, so it won't show Cx traffic. FHoSS's own log"
echo "  location depends on how it's deployed -- e.g. a Tomcat instance under"
echo "  /var/log/tomcat*/ or catalina.out, or wherever its own startup script points --"
echo "  check whatever process section above finds for its working directory/args.)"

echo
echo "== 3. Kamailio P-CSCF/I-CSCF/S-CSCF logs =="
echo "  Log destination depends on your install (syslog by default for Kamailio)."
echo "  In separate terminals, re-run register_test.py while tailing:"
echo "    journalctl -u kamailio_pcscf -f"
echo "    journalctl -u kamailio_icscf -f"
echo "    journalctl -u kamailio_scscf -f"
echo "  or, if these run as plain daemons logging to syslog:"
echo "    tail -f /var/log/syslog | grep -Ei 'pcscf|icscf|scscf'"
echo
echo "  What to look for, in order:"
echo "    - Does I-CSCF log show it picked an S-CSCF from its capability table"
echo "      (icscf.sql's s_cscf_uri), or does it fail to find/reach one?"
echo "    - Does S-CSCF log show it sending a Cx MAR, or does it reject locally"
echo "      before ever contacting the HSS?"
echo "    - Any Diameter CER/CEA (Capabilities-Exchange) failures/timeouts between"
echo "      I-CSCF/S-CSCF and the HSS -- often an FQDN or Realm mismatch between"
echo "      icscf.xml/scscf.xml's <Peer FQDN=... Realm=.../> and whatever your HSS's"
echo "      own freeDiameter config (/etc/freeDiameter/hss.conf, not in the zip you"
echo "      gave me, so I can't check this half directly) actually advertises."
