#!/usr/bin/env bash
# Run this ON the baremetal core/IMS host, ideally right after reproducing a
# failed REGISTER with sip/register_test.py, to gather the evidence needed to
# tell WHERE in the chain a rejection like:
#   403 Forbidden - Private identity not found (Authorization: username)
# is actually coming from. That message is generated by Kamailio's IMS
# registrar logic once it has a username to look up -- so seeing it (rather
# than a routing failure/timeout) means a node DID engage with the identity
# and could not resolve it. The three live possibilities, in likely order:
#   1. The subscriber doesn't exist in the HSS/subscriber DB at all yet.
#   2. It exists for 5G (AMF/SMF slice+DNN) but has no IMS/Cx profile, so the
#      HSS's Cx lookup (User-Authorization or Multimedia-Auth) comes back
#      "unknown user" even though the IMSI is real.
#   3. The S-CSCF/I-CSCF <-> HSS Cx Diameter peer connection itself never
#      came up (FQDN/realm mismatch), so no Cx request could even be sent.
# This script can only check #1 mechanically and surface the HSS log (which
# is the only log path we know for certain from your config); it prints
# guidance for #2/#3 rather than guessing, since Kamailio's own log
# destination depends on your install.
set -uo pipefail

IMSI="${1:-001010000000001}"

echo "== 0. Is anything actually listening on the Cx Diameter port (3868)? =="
if command -v ss >/dev/null 2>&1; then
    hit=$(sudo ss -ltnp 2>/dev/null | grep ':3868 ' || true)
    if [ -n "$hit" ]; then
        echo "  Something is listening on :3868 -- good, at least a Cx server process exists:"
        echo "$hit" | sed 's/^/  /'
    else
        echo "  NOTHING is listening on :3868 anywhere on this host."
        echo "  That alone fully explains a 403 'Private identity not found': I-CSCF/S-CSCF"
        echo "  have a Diameter peer configured for hss.ims.mnc001.mcc001.3gppnetwork.org:3868"
        echo "  (see icscf.xml / scscf.xml), but there is no HSS process actually serving Cx"
        echo "  for them to talk to. open5gs's own hssd is Mongo-backed and, per your"
        echo "  systemctl status, isn't even running -- so if you intended a separate"
        echo "  MySQL-backed Cx HSS (e.g. the Open IMS Core 'FHoSS'), check whether that"
        echo "  service is installed and running at all."
    fi
else
    echo "  'ss' not available -- try: sudo lsof -i :3868   or   sudo netstat -ltnp | grep 3868"
fi

echo
echo "== 0b. MySQL databases present (best-effort; may need credentials) =="
if command -v mysql >/dev/null 2>&1; then
    dbs=$( (sudo mysql -N -e "SHOW DATABASES;" 2>/dev/null) || (mysql -N -u root -p -e "SHOW DATABASES;" 2>/dev/null) || true)
    if [ -n "$dbs" ]; then
        echo "$dbs" | sed 's/^/  /'
        echo "  For any DB above that looks HSS/IMS-related (not 'icscf' -- that one is only"
        echo "  I-CSCF's static S-CSCF routing table, no subscriber data), list its tables:"
        echo "    sudo mysql -N -e \"SHOW TABLES FROM <dbname>;\""
        echo "  and look for something like IMS_SUBSCRIPTION / PUBLIC_IDENTITY / PRIVATE_IDENTITY"
        echo "  (classic FHoSS/Open IMS Core schema) -- that's where imsi-${IMSI}'s IMS profile"
        echo "  (private + public identity, auth data) would need a row."
    else
        echo "  Could not list databases without credentials. Run manually:"
        echo "    sudo mysql -e 'SHOW DATABASES;'"
    fi
else
    echo "  mysql client not on PATH."
fi

echo
echo "== 1. Does subscriber imsi-${IMSI} exist, and does it have IMS/Cx data? =="
if command -v open5gs-dbctl >/dev/null 2>&1; then
    out=$(open5gs-dbctl showall 2>/dev/null)
    if echo "$out" | grep -q "\"imsi\" : \"${IMSI}\""; then
        echo "  FOUND in subscriber DB. Full record (check for an ims/msisdn/IMS-profile"
        echo "  block below vs. only slice/session data -- absence of an IMS profile is"
        echo "  possibility #2 above):"
        echo "$out" | grep -B2 -A40 "\"imsi\" : \"${IMSI}\""
    else
        echo "  NOT FOUND. This alone would fully explain the 403 -- the HSS has no"
        echo "  record to answer a Cx lookup with. Provision it first:"
        echo "    ../scripts/provision_test_subscriber.sh"
    fi
else
    found=$(command -v find >/dev/null 2>&1 && sudo find / -xdev -name "open5gs-dbctl*" -type f 2>/dev/null | head -1)
    if [ -n "${found:-}" ]; then
        echo "  open5gs-dbctl not on PATH but found at: $found"
        echo "    sudo $found showall | grep -B2 -A40 '\"imsi\" : \"${IMSI}\"'"
    else
        echo "  open5gs-dbctl not found. Since open5gs-webui is active on this host, the"
        echo "  easiest check is the WebUI itself: http://<core-host>:3000 (default"
        echo "  admin/1423) -> Subscriber -> search imsi-${IMSI}."
        echo "  (Note: this only covers the 5G/Mongo side -- open5gs's own hssd isn't"
        echo "  running per your systemctl status, so this subscriber DB is NOT what"
        echo "  Kamailio's Cx lookup queries. See section 0/0b below for the actual"
        echo "  Cx-serving HSS.)"
    fi
fi

echo
echo "== 2. HSS log (last 200 lines) -- look for Cx traffic around your test's timestamp =="
if [ -r /var/log/open5gs/hss.log ]; then
    tail -n 200 /var/log/open5gs/hss.log
    echo
    echo "  Look for: Multimedia-Auth-Request/Answer or User-Authorization-Request/Answer"
    echo "  around the time you ran register_test.py, and what result code came back"
    echo "  (DIAMETER_SUCCESS vs DIAMETER_ERROR_USER_UNKNOWN / DIAMETER_ERROR_IDENTITIES_DONT_MATCH)."
    echo "  If you see NOTHING at all for that timestamp, the Cx request never reached"
    echo "  the HSS -- that points at #3 (peer connection down) rather than #1/#2."
else
    echo "  /var/log/open5gs/hss.log not readable from here."
    echo "  Run this script as root/with sudo on the core host, or check the path"
    echo "  configured under 'logger: file: path:' in hss.yaml if it was changed."
fi

echo
echo "== 3. Kamailio P-CSCF/I-CSCF/S-CSCF logs =="
echo "  Log destination depends on your install (syslog by default for Kamailio)."
echo "  In separate terminals, re-run register_test.py while tailing:"
echo "    journalctl -u kamailio_pcscf -f"
echo "    journalctl -u kamailio_icscf -f"
echo "    journalctl -u kamailio_scscf -f"
echo "  or, if these run as plain daemons logging to syslog:"
echo "    tail -f /var/log/syslog | grep -Ei 'pcscf|icscf|scscf'"
echo
echo "  What to look for, in order:"
echo "    - Does I-CSCF log show it picked an S-CSCF from its capability table"
echo "      (icscf.sql's s_cscf_uri), or does it fail to find/reach one?"
echo "    - Does S-CSCF log show it sending a Cx MAR, or does it reject locally"
echo "      before ever contacting the HSS?"
echo "    - Any Diameter CER/CEA (Capabilities-Exchange) failures/timeouts between"
echo "      I-CSCF/S-CSCF and the HSS -- often an FQDN or Realm mismatch between"
echo "      icscf.xml/scscf.xml's <Peer FQDN=... Realm=.../> and whatever your HSS's"
echo "      own freeDiameter config (/etc/freeDiameter/hss.conf, not in the zip you"
echo "      gave me, so I can't check this half directly) actually advertises."
