logger:
  file:
    path: /var/log/open5gs/upf.log
upf:
  pfcp:
    server:
      - address: 127.0.0.7
  gtpu:
    server:
      - address: 172.17.9.48
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
    - subnet: cafe::/48
      dnn: internet
    - subnet: 10.46.0.0/16
      gateway: 10.46.0.1
      dnn: ims
    - subnet: cafe:1::/48
      dnn: ims
  metrics:
    server:
      - address: 127.0.0.7
        port: 9090
